# Generated by Django 5.1.6 on 2025-02-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("item", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "table_number",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3")],
                        verbose_name="Номер стола",
                    ),
                ),
                (
                    "total_price",
                    models.PositiveIntegerField(verbose_name="Общая стоимость заказа"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "В ожидании"),
                            ("ready", "Готово"),
                            ("paid", "Оплачено"),
                        ],
                        default="В ожидании",
                        max_length=20,
                        verbose_name="Статус заказа",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания заказа"
                    ),
                ),
                (
                    "items",
                    models.ManyToManyField(
                        related_name="items",
                        to="item.item",
                        verbose_name="Список заказанных блюд с ценами",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
            },
        ),
    ]
