# Generated by Django 5.1.6 on 2025-02-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_alter_order_total_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("в ожидании", "В ожидании"),
                    ("готово", "Готово"),
                    ("оплачено", "Оплачено"),
                ],
                default="В ожидании",
                max_length=20,
                verbose_name="Статус заказа",
            ),
        ),
    ]
